### ISSUE TITLE
Consider using Strong naming for the assemblies.

### ISSUE THREAD

**Issue by DexterWoo** [iAJTin/iSMBIOS#4]
According to this MSDN document: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming 

One important aspect of strong naming is that it's viral: a strong named assembly can only reference other strong named assemblies. **If your library isn't strong named, then you have excluded developers who are building an application or library that needs strong naming from using it.**

The benefits of strong naming are:

The assembly can be referenced and used by other strong-named assemblies.
The assembly can be stored in the Global Assembly Cache (GAC).
The assembly can be loaded side by side with other versions of the assembly. Side-by-side assembly loading is commonly required by applications with plug-in architectures.

non-strong naming assemblies can reference strong naming assemblies, but strong naming assemblies can only reference strong naming assemblies.

to allow most users to be able to use this library, I recommend use a snk file to sign the assembly projects.  what needs to be done here is to create a snk file and share across the projects that are being packing into nuget package.

 All other popular .net nuget packages are using this approach now.

**Comment by iAJTin** [comment]
Hi @DexterWoo, thanks for the observation, I have updated the nuget package where the assemblies are signed. I hope it helps you !!

I take this opportunity to tell you that in this iteration the logic has been separated into different assemblies, so that now the smbios implementation is self-contained in its own assembly, as well as the DMI specification in its own, and the TPM assembly that uses structure 43 of the SMBIOS specification.

Please check the CHANGELOG file for more information.

I also wanted to take advantage, to invite you to use the new nuget iEEDID package to obtain the EDID information (currently only the information is parsed, in later iterations it will self-detect it)

NOTE:
Despite the structural changes, everything should continue to function properly without making any changes.


A greeting!

**Comment by DexterWoo** [comment]
@iAJTin   that's very great! I have integrated the lasted version, and it works very well.
