### ISSUE TITLE
nuget 1.1.0 libs identical with 1.0.9

### ISSUE THREAD

**Issue by DexterWoo** [iAJTin/iSMBIOS#5]
recently when debugging an issue, I found that nuget 1.1.0 and 1.0.9 are identical.
![image](https://user-images.githubusercontent.com/11514478/67065548-4ae41100-f1a1-11e9-9ed5-4dd11fdb0406.png)
--> this means the nuget 1.1.0 is actually the same as 1.0.9 in the end.
and I found that none of the libs carries version information, they are all 1.0.0.0
which will make it a bit difficult to track which version is in use when not looking in the source code.

my suggestion would be to create a build pipeline and mark the release versions during build.
any thought? @iAJTin

**Comment by iAJTin** [comment]
Hi Dexter, sorry for the delay, I could not see what you said,
I'm a little surprised, allow me to investigate it, but I think you're right, I made a mistake and I think both are the same, right now I'm adding version 3.3.0 of the specification, I will update as soon as possible.

As for the topic of complementary libraries, it is a problem that I have not yet addressed, I have to find a simple way to version them, since it forces me to keep many versions, since they are shared with several projects (nuget packages),

But I agree with you, I have to fix it

**Comment by iAJTin** [comment]
Hi Dexter, Updated nuget package to v1.1.1, includes

- Adds support for System Management BIOS (SMBIOS) v3.3.0, includes:

      * System Slots (Type 9):
        - SMBIOSCR00184: add PCI Express Gen 4 values
        - SMBIOSCR00185: clarify bus number usage for PCI Express
      * Memory Device (Type 17):
        - SMBIOSCR00178: add new memory device type value (HBM) and new form factor value (Die)
        - SMBIOSCR00179: update the string for Intel persistent memory
      * Various:
        - SMBIOSCR00181: add support for RISC-V processors, add structure type 44 (processor-additional information)
        - SMBIOSCR00183: add support for CXL Flexbus

### Changed

- Library versions for this version
  
|Library|Version|Description|
|:------|:------|:----------|
|iTin.Core| 1.0.0 | Common calls |
|iTin.Core.Interop| 1.0.0 | Interop calls |
|iTin.Core.Hardware| 1.0.0 | Hardware Interop Calls |
|iTin.Core.Hardware.Specification.Dmi|3.3.0.0| DMI Specification Implementation |
|iTin.Core.Hardware.Specification.Smbios|3.3.0.0| SMBIOS Specification Implementation |
|iTin.Core.Hardware.Specification.Tpm|1.0.0| TPM Specification Implementation |

**Comment by DexterWoo** [comment]
@iAJTin  I've verified it,  everything is as expected now.
Thank you for the quick support.
