### ISSUE TITLE
IdentificationCode?

### ISSUE THREAD

**Issue by steingran** [iAJTin/iSMBIOS#6]
Hi,

There is a BIOS value named 'IdentificationCode', ref https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-bios. But I cannot see that the iSMBIOS library retrieves this value?

Best,
Stein J. Gran

**Comment by iAJTin** [comment]
Hi,
iSmbios tries to conform to the smbios version xx specification, I think wmi adds this field in the Bios structure, but in reality it must be an added value that microsoft incorporates into the structure, since in the specification I have not seen any mention made of said value.

Anyway, I will investigate a little more and as soon as I can give you the information, (but the impression it gives me is that it does not belong to the specification)

Thank you for the time you have spent looking at the library.

Greetings

**Comment by iAJTin** [comment]
Hi Stein,

As I mentioned in the previous message, I have been deepening your question, and I have not found that since the SMBIOS specification you have access to the property you need,

So I'm afraid that the property you need, the best way to get it is from WMI.

If you have any ideas ?, tell me, something happened to me anyway.

Greetings

**Comment by steingran** [comment]
Hi iAJTin,

Ok, thank you for looking into this, much appreciated 👍 

Best,
Stein J. Gran

**Comment by iAJTin** [comment]
.
